SECRET_KEY = 'FALSE-KEY-000'

S3_BUCKET_NAME = 'BucketName'
S3_AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID'
S3_AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY'
S3_LOCAL_PATH = 'S3_LOCAL_PATH'
S3_AWS_BASE_URL = 'http://s3.amazonaws.com/'
S3_CATEGORY_MAPPING = {
    'B': 'BACKGROUND',
    'F': 'VASES',
    'CF': 'CLIPPING-FLOWERS',
    'WF': 'WRAPPING-FLOWERS',
    'CR': 'CATALOGUE-PRODUCTS',
    'PP': 'PERSONALIZED-PRODUCTS',
    'CM': 'COMPOSITIONS'
}

INSTALLED_APPS = [
    'django_s3',
]

MIDDLEWARE_CLASSES = (
)
